# Generated by Django 4.0.7 on 2023-05-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_id_alter_relationship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
    ]
